name: UnifiedTaxSystem

services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - ${DATABASE_PORTS}
    environment:
      POSTGRES_USERNAME: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
