# Generated by Django 6.0.3 on 2026-03-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_money', models.IntegerField()),
                ('_tax_rate', models.PositiveSmallIntegerField()),
                ('_date', models.DateField()),
                ('_country', models.CharField(choices=[('Russia', 'Russia'), ('China', 'China')], max_length=100)),
                ('_payload', models.JSONField()),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
            },
        ),
    ]
